version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postBoss
      POSTGRES_DB: django_db
      POSTGRES_PASS: hackTheDb
    volumes:
      - pgdata:/var/lib/posgresql/data
  dist :
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./dist :/dist
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata:
