# Generated by Django 3.0.13 on 2021-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191220_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=DN0gAQQ7FAQ'),
            preserve_default=False,
        ),
    ]
