# Generated by Django 3.0.13 on 2021-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='author_email',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Author email'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Europe/Moscow', max_length=100, verbose_name='Book name'),
            preserve_default=False,
        ),
    ]
