# Generated by Django 3.0.13 on 2021-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20210307_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='buff.com'),
            preserve_default=False,
        ),
    ]
