# Generated by Django 3.0.13 on 2021-03-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20210307_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalogue.product',),
        ),
    ]
