# Generated by Django 3.0.13 on 2021-03-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20210307_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportExport',
        ),
    ]
