# Generated by Django 3.0.13 on 2021-03-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_delete_importexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.TextField(default='0000000000000', max_length=13),
            preserve_default=False,
        ),
    ]
