# Generated by Django 3.0.13 on 2021-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20210309_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.TextField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
