# Generated by Django 3.0.13 on 2021-03-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_importexportcategory_importexportproductcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importexportcategory',
            options={'verbose_name': 'Импорт и Экспорт Категорий'},
        ),
        migrations.AlterModelOptions(
            name='importexportproductcategory',
            options={'verbose_name': 'Импорт и Экспорт Категории продуктов'},
        ),
        migrations.AlterUniqueTogether(
            name='importexportproductcategory',
            unique_together=set(),
        ),
    ]
