# Generated by Django 3.0.13 on 2021-03-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20210315_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportExportCategory',
        ),
        migrations.DeleteModel(
            name='ImportExportProductCategory',
        ),
    ]
