# Generated by Django 3.0.13 on 2021-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20210315_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
