# Generated by Django 3.0.13 on 2021-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.TextField(default='null', max_length=13),
        ),
    ]
