# Generated by Django 3.0.13 on 2021-03-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_name_for_site',
        ),
    ]
