# Generated by Django 3.0.13 on 2021-03-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20210328_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
