# Generated by Django 3.0.13 on 2021-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_1',
            field=models.URLField(blank=True, default=''),
        ),
    ]
