# Generated by Django 3.0.13 on 2021-03-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_product_image_url_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url_1',
        ),
    ]
